version: "3.8"
services:
  dev:
    environment:
      - TZ=Asia/Tokyo
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - claude-code-bashhistory:/commandhistory
      - claude-code-config:/home/node/.claude
      - gh-config:/home/node/.config/gh
    ports:
      - "3000:3000"
    tty: true

volumes:
  # 共有volumeは自分のユースケースにあったものに変更しましょう
  # ホストマシンからsetup-shared-volumes.shを実行して作成すればひとまず動きます
  claude-code-bashhistory:
    external: true
  claude-code-config:
    external: true
  gh-config:
    external: true
